### PR TITLE
fix GreyMatterNiftiMasker target_img

### PR DESCRIPTION
**Pull request by atsuch**
Make sure to use --force when running main.py to redo the ICA with the GM mask!

### CODE REVIEW

**Comment by bcipolli** [comment]
Nice! Can you show some updated components, so I can see what the mask looks like?

**Comment by atsuch** [comment]
I'm running the main ICA now but here is one fig from qc so that you can see the mask :-)
fig001

**Comment by bcipolli** [comment]
Cool, so a little bit stricter. Glad to see it's working! :)

**Comment by atsuch** [comment]
The components look better too. Not surprisingly, they look more like neuronal network. I didn't keep the old components so can't compare strictly but I think we are getting a few more interesting-looking networks than before.

**Pull request merged**
